# clones IBC-Scouts/optimism, checks out the poc-develop branch, builds
# the ibc-interceptor binary and runs op-e2e tests.
name: Run op-e2e tests
on:
  workflow_dispatch:
# Disable these temporarily
#  push:
#    branches: [main]
#  pull_request:
#    paths:
#      - '**.go'
    
jobs:
  op-e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - uses: actions/checkout@master
      - name: Check out repo and build ibc-interceptor
        run: |
          make build-interceptor
          git clone https://github.com/IBC-Scouts/optimism.git
          cd optimism
          git checkout poc-develop

      - name: Copy ibc-interceptor to optimism/op-e2e
        run: cp build/interceptor optimism/op-e2e

      # Required for op build.
      - uses: pnpm/action-setup@v3
        with:
          version: 8

      # Directly install based on .nvmrc
      - uses: actions/setup-node@v4.0.2
        with:
          node-version: 20.9.0

      - name: Install Foundry
        run: |
            curl -L https://foundry.paradigm.xyz | bash

      # Sourcing the bashrc and executing foundryup didn't work. No clue why but wont spend time on it.
      # Use commit in .foundryrc file.
      - name: Run foundryup
        run: |
          /home/runner/.config/.foundry/bin/foundryup --commit 53b15e6cee787a7765988bb7228f26f62eb78129

      - name: Build optimism devnet
        run: |
            export PATH=$PATH:/home/runner/.config/.foundry/bin
            pnpm i && pnpm build
            make install-geth
            make cannon-prestate
            make devnet-allocs
        working-directory: optimism/

      - name: Run op-e2e tests
        run: |
            go test -v -run TestDepositTxCreateContract ./...
        working-directory: optimism/op-e2e